export { default as PersonalFollow } from "./follow";
export { default as PersonalBody } from "./body";
export { default as PersonalGallery } from "./gallery";
export { default as PersonalHeader } from "./header";
export { default as PersonalIntroduce } from "./introduce";
export { default as PersonalNavbarProfile } from "./navbar-profile";
export { default as PersonalGeneralInfo } from "./general-info";
export { default as PersonalGalleryCollection } from "./gallery-collection";
export { default as PersonalSendMsgBtn } from "./send-msg-btn";
