const RouteNames = {
  HOME: "/",
  MESSAGE_PAGE: "/messages",
  ADMIN: "https://www.youtube.com/c/TheBrowserCompany",
  MEETING: "https://meet-with-us.netlify.app/",
  PERSONAL_PAGE: "/user/:userID",
  PERSONAL_PHOTOS: "/user/:userID/:photos",
  NOTIFICATION: "/notification",
  BOOKMARKS: "/bookmarks",
  POST_PREVIEW: "/post/:postID",
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  TERM_AND_SERVICE: "/term-and-service",
  COOKIE_POLICY: "/cookie-policy",
  PRIVACY_POLICY: "/privacy-policy",
  EXPLORE: "/explore",
  INSTAGRAM: "https://www.instagram.com/",
  FACEBOOK: "URL_ADDRESS",
  TWITTER: "https://twitter.com/",
  YOUTUBE: "https://www.youtube.com/channel/@",
  GITHUB: "https://github.com/",
  LINKEDIN: "https://www.linkedin.com/in/",
  PINTEREST: "https://www.pinterest.com/",
  TIKTOK: "URL_ADDRESS",
  WEIBO: "URL_ADDRESS",
  WECHAT: "URL_ADDRESS",
  QQ: "URL_ADDRESS",
  TWITCH: "https://www.twitch.tv/",
  TELEGRAM: "URL_ADDRESS",
  DISCORD: "URL_ADDRESS",
  SKYPE: "URL_ADDRESS",
  WHATSAPP: "URL_ADDRESS",
  FACEBOOK_MESSENGER: "URL_ADDRESS",
};

export { RouteNames };
