export const UserInitialize = {
    _id: "",
    username: "",
    profilePicture: "",
    coverPicture: "",
    followers: [],
    followings: [],
    bio: "",
    insta: "",
    linkedin: "",
    github: "",
    pinterest: "",
    youtube: "",
    twitter: "",
    twitch: "",
    postShared: [],
    blackList: [],
    postSaved: [],
    isVerify: false,
}
