export const MENU_NAME = {
  HOME: "HOME",
  ABOUT: "ABOUT",
  SETTINGS: "SETTINGS",
  PROFILE: "PROFILE",
  LOGOUT: "LOGOUT",
  DASHBOARD: "DASHBOARD",
  ADMIN: "ADMIN",
  USER: "USER",
  ADMIN_DASHBOARD: "ADMIN DASHBOARD",
  THEME: "THEME",
};
